curl -X GET http://localhost:3000/users




###Requisição de Registro
curl -X POST http://localhost:3000/register -H "Content-Type: application/json" -d '{"name": "Pedro", "email": "Pedro@example.com", "password": "senhaSeguraa"}'

###Requisição de login
curl -X POST http://localhost:3000/login -H "Content-Type: application/json" -d '{"email": "Pedro@example.com", "password": "senhaSeguraa"}'

###requisição login
curl -X POST http://localhost:3000/login -H "Content-Type: application/json" -d '{"email": "joao@example.com", "password": "senhaSegura"}'

###aaaa
curl -X POST http://localhost:3000/register -H "Content-Type: application/json" -d '{"name": "João", "email": "joao@example.com", "password": "senhaSegura"}'

###aaaa
